[package]
name = "psrs-linker"
version.workspace = true
edition.workspace = true
license.workspace = true

[[test]]
name = "guest"
path = "tests/guest/mod.rs"

[dependencies]
psrs-runtime = { workspace = true, default-features = false, features = ["catalog", "gc-storage"] }
sha2 = "=0.10.9"
wasm-encoder.workspace = true
wasmparser.workspace = true
wit-component = "=0.245.1"
wit-parser = "=0.245.1"
wasm-compose = "=0.245.1"

[dev-dependencies]
wasmprinter.workspace = true
wat = "=1.245.1"
