use super::*;

pub(super) fn declarations() -> Vec<(&'static str, TypeDeclaration)> {
    vec![
        (
            "Prim.TypeError",
            foreign_type(
                TypeId::PRIM_TYPE_ERROR_DOC,
                "Doc",
                builtin(BuiltinType::Type),
                &[],
            ),
        ),
        (
            "Prim.TypeError",
            class(
                TypeId::PRIM_TYPE_ERROR_FAIL,
                "Fail",
                &["message"],
                function_kind(vec![named(TypeId::PRIM_TYPE_ERROR_DOC)]),
                Vec::new(),
            ),
        ),
        (
            "Prim.TypeError",
            class(
                TypeId::PRIM_TYPE_ERROR_WARN,
                "Warn",
                &["message"],
                function_kind(vec![named(TypeId::PRIM_TYPE_ERROR_DOC)]),
                Vec::new(),
            ),
        ),
        // `Text`, `Quote`, `QuoteLabel`, `Beside`, and `Above` are phantom at
        // every parameter: they only build a `Doc`, so `Coercible` accepts two
        // arguments that differ solely in a phantom position.
        (
            "Prim.TypeError",
            foreign_type(
                TypeId::PRIM_TYPE_ERROR_TEXT,
                "Text",
                arrow_kind(
                    vec![builtin(BuiltinType::Symbol)],
                    named(TypeId::PRIM_TYPE_ERROR_DOC),
                ),
                &[Role::Phantom],
            ),
        ),
        (
            "Prim.TypeError",
            foreign_type(
                TypeId::PRIM_TYPE_ERROR_QUOTE,
                "Quote",
                forall_kind_result("k", vec![variable("k")], named(TypeId::PRIM_TYPE_ERROR_DOC)),
                &[Role::Phantom],
            ),
        ),
        (
            "Prim.TypeError",
            foreign_type(
                TypeId::PRIM_TYPE_ERROR_QUOTE_LABEL,
                "QuoteLabel",
                arrow_kind(
                    vec![builtin(BuiltinType::Symbol)],
                    named(TypeId::PRIM_TYPE_ERROR_DOC),
                ),
                &[Role::Phantom],
            ),
        ),
        (
            "Prim.TypeError",
            foreign_type(
                TypeId::PRIM_TYPE_ERROR_BESIDE,
                "Beside",
                arrow_kind(
                    vec![
                        named(TypeId::PRIM_TYPE_ERROR_DOC),
                        named(TypeId::PRIM_TYPE_ERROR_DOC),
                    ],
                    named(TypeId::PRIM_TYPE_ERROR_DOC),
                ),
                &[Role::Phantom, Role::Phantom],
            ),
        ),
        (
            "Prim.TypeError",
            foreign_type(
                TypeId::PRIM_TYPE_ERROR_ABOVE,
                "Above",
                arrow_kind(
                    vec![
                        named(TypeId::PRIM_TYPE_ERROR_DOC),
                        named(TypeId::PRIM_TYPE_ERROR_DOC),
                    ],
                    named(TypeId::PRIM_TYPE_ERROR_DOC),
                ),
                &[Role::Phantom, Role::Phantom],
            ),
        ),
    ]
}
