import type { Pass } from './types';

export const passes: Pass[] = [
  { id: 'p0-lex-layout', ordinal: 0, name: 'Lex and Layout', input: 'source', output: 'tokens', kind: 'boundary', purpose: 'Recognize raw tokens and insert indentation-derived layout markers.', guarantees: ['Token spelling and source ranges remain recoverable.', 'Layout markers make offside-rule blocks explicit for parsing.'], exclusions: ['It does not construct syntax.', 'It does not resolve names or infer types.'], nearestCommand: 'cargo run -- lex examples/basic.purs' },
  { id: 'p1-parse', ordinal: 1, name: 'Parse', input: 'tokens', output: 'cst', kind: 'boundary', purpose: 'Build source-oriented concrete syntax and report parse errors.', guarantees: ['Concrete forms and relevant token ranges survive.', 'No semantic assumptions are required.'], exclusions: ['CST does not contain IDs, types, evidence, or layouts.'], nearestCommand: 'cargo run -- parse examples/basic.purs' },
  { id: 'p2-surface-lowering', ordinal: 2, name: 'Surface Lowering', input: 'cst', output: 'ast', kind: 'boundary', purpose: 'Normalize parser-only syntax into the abstract surface language.', guarantees: ['Unresolved names and source spans survive.', 'Syntax-only distinctions may be removed.'], exclusions: ['AST is not an alias for CST.', 'Names are not resolved here.'], nearestCommand: 'cargo run -- ast examples/basic.purs' },
  { id: 'p3-resolve', ordinal: 3, name: 'Resolve', input: 'ast', output: 'hir', kind: 'boundary', purpose: 'Resolve modules, declarations, constructors, and locals to stable IDs.', guarantees: ['Every successful reference has a stable identity.', 'Source ranges remain available for diagnostics.'], exclusions: ['HIR has no inferred types or backend layout.'], nearestCommand: 'cargo run -- hir examples/resolved.purs' },
  { id: 'p4-desugar', ordinal: 4, name: 'Frontend Desugaring', input: 'hir', output: 'hir', kind: 'same-representation', purpose: 'Normalize operators, sections, do/ado, equations, and guards while preserving HIR.', guarantees: ['Resolved IDs stay valid.', 'The input and output are both HIR.'], exclusions: ['It does not introduce a new long-lived IR family.'] },
  { id: 'p5-kind-type', ordinal: 5, name: 'Kind, Type, and Class Elaboration', input: 'hir', output: 'thir', kind: 'boundary', purpose: 'Check kinds and types and attach explicit constraint evidence.', guarantees: ['Expressions and binders carry checked types.', 'Constraints become explicit semantic evidence.'], exclusions: ['THIR has no runtime offsets, Wasm indices, or calling conventions.'], nearestCommand: 'cargo run -- check examples/basic.purs' },
  { id: 'p6-core-lowering', ordinal: 6, name: 'Core Lowering', input: 'thir', output: 'core', kind: 'boundary', purpose: 'Remove surface constructs and lower patterns and dictionaries to a small typed Core.', guarantees: ['Types and stable IDs remain explicit.', 'Source sugar is eliminated.'], exclusions: ['Core does not choose runtime representation.'], nearestCommand: 'cargo run -- dump core examples/basic.purs' },
  { id: 'p7-core-simplify', ordinal: 7, name: 'Core Simplify and Specialize', input: 'core', output: 'core', kind: 'same-representation', purpose: 'Optimize and specialize without changing the Typed Core contract.', guarantees: ['Input and output are Typed Core.', 'Semantic equivalence is preserved.'], exclusions: ['Optimization must not add backend fields to Core.'] },
  { id: 'p8-anf-closure', ordinal: 8, name: 'ANF and Closure Conversion', input: 'core', output: 'cc', kind: 'boundary', purpose: 'Make evaluation order, captures, and call modes explicit.', guarantees: ['Non-trivial computations are named.', 'Direct and closure calls are distinct.'], exclusions: ['ANF is a CC IR form, not a separate family.'], nearestCommand: 'cargo run -- dump cc examples/basic.purs' },
  { id: 'p9-representation', ordinal: 9, name: 'Representation Lowering', input: 'cc', output: 'mir', kind: 'boundary', purpose: 'Choose runtime layouts and lower into an explicit control-flow graph.', guarantees: ['Blocks, values, instructions, and terminators are explicit.', 'MIR fixes layouts and calling conventions.'], exclusions: ['MIR has no nested source expression trees or implicit closures.'], nearestCommand: 'cargo run -- dump mir examples/basic.purs' },
  { id: 'p10-wasm-structuring', ordinal: 10, name: 'MIR Optimization and Wasm Structuring', input: 'mir', output: 'wasm', kind: 'target-encoding', purpose: 'Optimize CFG and structure its control flow for Wasm emission.', guarantees: ['Control flow becomes structured.', 'Leaf opcodes remain delegated to the Wasm encoder.'], exclusions: ['Structured Wasm is not a long-lived IR family.'] },
  { id: 'p11-validate-link', ordinal: 11, name: 'Validate and Link', input: 'wasm', output: 'artifact', kind: 'target-encoding', purpose: 'Validate, encode, print WAT, and connect runtime and WASI interfaces.', guarantees: ['The emitted artifact is target-valid.', 'Only required interfaces are linked.'], exclusions: ['The artifact is an output, not another compiler IR.'] },
];

export const passById = Object.fromEntries(passes.map((pass) => [pass.id, pass]));
