import type { Representation } from './types';

export const representations: Representation[] = [
  { id: 'source', name: 'Source', family: 'Source', lifecycle: 'source', purpose: 'The program as a person wrote it.', invariant: 'The original program text is authoritative for spelling and trivia.', contains: ['characters', 'comments', 'exact spelling'], excludes: ['parsed structure', 'semantic facts'], rationale: 'It is the common reference for diagnostics and source tools.' },
  { id: 'tokens', name: 'TokenStream', family: 'Parser input', lifecycle: 'temporary', purpose: 'Turn characters into parser-ready units.', invariant: 'Raw tokens plus virtual layout markers; not a persistent IR family.', contains: ['token kinds', 'source ranges', 'layout markers'], excludes: ['syntax tree', 'resolved names'], rationale: 'It exists only to make parsing and indentation rules explicit.' },
  { id: 'cst', name: 'CST', family: 'CST', lifecycle: 'long-lived', purpose: 'Preserve the program’s written syntax.', invariant: 'Concrete syntax and diagnostic token ranges remain available; no semantic facts.', contains: ['parentheses', 'keywords', 'operators', 'token spans'], excludes: ['resolved IDs', 'types', 'runtime layout'], rationale: 'Source-facing tools need to see what the parser actually recognized.' },
  { id: 'ast', name: 'AST', family: 'AST', lifecycle: 'long-lived', purpose: 'Keep surface meaning while discarding parser-only detail.', invariant: 'Parser-only distinctions are normalized; names remain unresolved and spanned.', contains: ['normalized expressions', 'unresolved names', 'source spans'], excludes: ['concrete punctuation', 'semantic IDs', 'types'], rationale: 'Later frontend passes should not need to reason about parentheses or grammar accidents.' },
  { id: 'hir', name: 'Resolved HIR', family: 'HIR', lifecycle: 'long-lived', purpose: 'Give every semantic reference a stable identity.', invariant: 'Names have stable declaration or local IDs and source spans remain available.', contains: ['symbol IDs', 'local IDs', 'module relationships'], excludes: ['inferred types', 'runtime layout'], rationale: 'Semantic passes must not infer identity from text spelling.' },
  { id: 'thir', name: 'THIR', family: 'THIR', lifecycle: 'long-lived', purpose: 'Record checked high-level meaning.', invariant: 'Expressions and binders have checked types and explicit semantic evidence.', contains: ['types', 'resolved IDs', 'constraint evidence'], excludes: ['Wasm indices', 'memory offsets', 'calling convention'], rationale: 'Type-driven decisions belong above the backend boundary.' },
  { id: 'core', name: 'Typed Core', family: 'Typed Core', lifecycle: 'long-lived', purpose: 'Express programs in a small typed functional language.', invariant: 'A small typed functional language without surface sugar or pattern syntax.', contains: ['lambdas', 'applications', 'cases', 'typed primitives'], excludes: ['surface syntax', 'implicit dictionaries', 'runtime layout'], rationale: 'It is the stable semantic hand-off from frontend to backend.' },
  { id: 'cc', name: 'CC IR', family: 'CC IR / MIR', lifecycle: 'long-lived', purpose: 'Make evaluation order and closures explicit.', invariant: 'Evaluation order, captures, and direct versus closure calls are explicit.', contains: ['ANF bindings', 'captures', 'call mode'], excludes: ['implicit lambda captures', 'nested non-trivial evaluation'], rationale: 'Backends need explicit control over evaluation and closure data.' },
  { id: 'mir', name: 'MIR / CFG', family: 'CC IR / MIR', lifecycle: 'long-lived', purpose: 'Choose runtime representation and explicit control flow.', invariant: 'Typed blocks, values, instructions, terminators, layouts, and call conventions are fixed.', contains: ['basic blocks', 'values', 'terminators', 'layouts'], excludes: ['nested source expressions', 'implicit closures'], rationale: 'It is the lowest long-lived representation before target encoding.' },
  { id: 'wasm', name: 'Structured Wasm', family: 'Target encoding', lifecycle: 'temporary', purpose: 'Express MIR control flow in the shape Wasm requires.', invariant: 'A thin, structured target form used only between MIR and binary emission.', contains: ['module skeleton', 'structured regions', 'Wasm instructions'], excludes: ['a new persistent IR family', 'frontend facts'], rationale: 'It is an emission aid, not a representation with independent compiler ownership.' },
  { id: 'artifact', name: '.wasm / WASI artifact', family: 'Artifact', lifecycle: 'artifact', purpose: 'Deliver a validated executable component.', invariant: 'A validated target artifact with only the required runtime interfaces.', contains: ['encoded module', 'component metadata', 'WASI imports'], excludes: ['compiler analysis state', 'editable IR structure'], rationale: 'This is the output consumed by a compatible runtime.' },
];

export const representationById = Object.fromEntries(
  representations.map((representation) => [representation.id, representation]),
) as Record<Representation['id'], Representation>;
